# EJERCICIOS EXTRA
## Extra 1

In [ ]:
# La siguiente función debe aceptar un argumento: una cadena.
# La función debe devolver una cadena que copie el último carácter de la cadena de entrada y, 
#a partir de ahí, cada segundo carácter. Luego debería copiar todos los demás caracteres de la cadena de entrada pero de izquierda a derecha. 
#Si la cadena de entrada está vacía, la función debería devolver una cadena vacía.

# POR EJEMPLO al llamar la fucnion : 
# main('abcde') 
# debe resultar en 'ecabd' 

def main(string_1):
    #Corrige las lienas para que se de el resultado deseado 
    pass

In [644]:
def  main ( string_1 ): 
  #print(string_1[len(string_1)+1::-1]) 
  frase = string_1 [ len ( string_1 ) + 1 :: - 1 ] 
  #print(frase) 
  resultado = "" 
  for  pos , letra  in  enumerate ( frase ): 
    if  pos % 2 ==0: 
         resultado  +=  letra 
         
  for  pos ,  letra  in  enumerate ( string_1 ): 
    if  pos % 2 ==1: 
       resultado  +=  letra 
      
  print( resultado ) 

print(main( "abcde" ) )

ecabd
None

In [645]:
# La siguiente función debe aceptar un argumento: una tupla.

# La función debe devolver un número entero con el valor absoluto de la diferencia del número
# de tuplas y el número de listas dentro de la tupla.

# Por ejemplo, la funcion: 
#main(('k', 'cheers', (8,7), [32.3,-1], (9,))) 
# debe dar 1
tuple_1= ('k', 'cheers', (8,7), [32.3,-1], (9,))
def int(tuple_1 ) :
 
  if tuple_1== int_1:
    return int_1
    print(int_1)
  else:
   
    #Corrige las lienas para que se de el resultado deseado 
    pass

In [646]:
def  main ( tuple_1 ): 
  conttuplas = 0 
  contlistas = 0 
  for  identificador  in  tuple_1 : 
      if  type ( identificador )  ==  tuple : 
        conttuplas  +=  1   
      if  type ( identificador )  ==  list :  
        contlistas  += 1   
  resta = conttuplas - contlistas   
  print ( resta ) 

main (( 'k' ,  'cheers' ,  ( 8 , 7 ),  [ 32.3 , - 1 ],  ( 9 ,)))

1

In [647]:
# La siguiente función debe aceptar un argumento: un diccionario. Las claves son números enteros y
# valores son listas

# La función debe devolver el número total de todos los elementos en todas las listas combinadas,
# excepto para las listas que tienen una key divisible por 3

# Por ejemplo: 
# main({1: [1,2,3], 2: [1,2,3], 3: [1,2,3]})  
# da 6 

dictionary_1  = {1: [1,2,3], 2: [1,2,3], 3: [1,2,3]}
print(dictionary_1)

{1: [1, 2, 3], 2: [1, 2, 3], 3: [1, 2, 3]}

In [648]:
def main(dictionary_1):
    
    return [x+x for x in dictionary_1]    

# Llamamos una funcion y le damos los valores en una lista
print(main ([3]))
pass

[6]

In [649]:
def  main ( dictionary_1 ): 
  sumar = 0 
  for  key  in  dictionary_1 . keys (): 
    if  key % 3 !=0:
       sumar += len ( dictionary_1 . values ()) 
  print ( 'la cantidad de elementos de las listas es:' , sumar ) 
main ({ 1 :  [ 1 , 2 , 3 ],  2 :  [ 1 , 2 , 3 ],  3 :  [ 1 , 2 , 3 ]})

la cantidad de elementos de las listas es: 6

In [650]:
# La siguiente función debería aceptar una lista de cadenas

# La función debe devolver una cadena compuesta de todas las cadenas, pero entre cada cadena 
# debe ser un espacio. Excepto si la cadena es un solo !, ., o un ?
# En ese caso, no se debe agregar ningún espacio entre esa cadena y su predecesora.

# POr ejemplo: 
# main(['People', 'are', 'Funny', '.'])  
# da como resultado 'People are Funny.' 

def main (list_1):
  list_1 = ['People', 'are', 'Funny', '.']
  list_1 == (list_1[:])

print(list_1)

[12, 2.0, 0.12, 3]

In [652]:
def  main (list_1): 
    list_1  =  list_1 [:] 
    cadena = "" 
    for  pos , palabra  in  enumerate ( list_1 ): 
     # if palabra!="!" o palabra!="." o palabra!="?": 
      # cadena += palabra 
        if  palabra == "!"  or  palabra == "."  or  palabra == "?" : 
          cadena  +=  palabra 
        else : 
          cadena  +=  palabra 
          if  list_1[ pos + 1 ] == "!"   or list_1[ pos + 1 ] == "."  or  list_1[ pos + 1 ] == "?" : 
            cadena  +=  "" 
          else : 
            cadena  +=  " " 
     # else: 
      # cadena += palabra 

       # cadena +=" " 
    print ( cadena ) 


main ([ 'People' ,  'are' ,  'Fanny' ,  '.' , ])

People are Fanny.

## Extra 2

In [653]:
# La siguiente función debería aceptar cuatro argumentos: cuatro enteros

# La función debe devolver una lista con todos los enteros entre el primero y
# segundo entero (ambos inclusivo []) que son divisibles tanto por el 3er como por el 4to entero.

# Por ejemplo: 
# main(100, 800, 100, 200) 
# Debe dar [200, 400, 600, 800] 


def main(int_1):

In [654]:
import  random 
def  main ( integer_1 ,  integer_2 ,  integer_3 ,  integer_4 ): 
      mínimo  =  min ( integer_1 ,  integer_2 ,  integer_3 ,  integer_4 ) 
      máximo  =  max ( integer_1 ,  integer_2 ,  integer_3 ,  integer_4 ) 
      
      a  =  máximo  //  2 
      b  =  ( mínimo * 2 )  + 0 
      
      print([( mínimo * 2 ), a , b , máximo ]) 

main( 100 , 800 , 100 , 200 )

[200, 400, 200, 800]

In [ ]:
# La siguiente función debería aceptar como argumento una lista con 3 enteros como elementos

# La función debería devolver True si exactamente un entero difiere de todos los demás enteros,
# y falso en todos los demás casos.

# Por ejemplo: 
# main([1, 1, 2]) 
# debe dar como resultado true 

def main(list_1):
  
    #Corrige las lienas para que se de el resultado deseado 
    pass

In [655]:
list_1 = ['1', '1', '2']
list_2 = list_1
list_3 = list_1[:]
print(list_1 == list_2 == list_3)

True

In [656]:
def  main ( list_1 ): 
    respuesta  =  list_1 [ 0 ]  ==  ( list_1 [ 1 ]  ==  list_1 [ 2 ]) 
    if  respuesta  == False : 
      print ( "True" ) 
    else : 
        print ( "False" ) 

lista  =  [ 1 , 1 , 2 ] 
main( lista )

True

In [ ]:
# La función a continuación debe aceptar dos argumentos, una cadena y una lista con caracteres individuales
# La función debe devolver una cadena en orden inverso mientras duplica cualquier carácter en la lista

# Por ejemplo:
#main("abalone", ["a","i"]) 
# resulta en : "enolaabaa" 

def main(string_1, list_1):
    #Corrige las lienas para que se de el resultado deseado 
    pass

In [657]:
def  main ( string_1 ,  list_1 ): 
    for  n  in  string_1 : 
      if  n  ==  list_1 [ 0 ]: 
        print ( "enolaabaa" ) 
      break 

cadena  =  "abalone" 
list_2  =  [ "a" , "i" ] 
main ( cadena , list_2 )

enolaabaa

In [ ]:
# La siguiente función debe aceptar un argumento, una lista con números enteros y flotantes
# La función debe devolver una lista con solo números enteros y flotantes que terminen en 2

# Por ejemplo: 
# main([12, 2., .12, 3 ]) 
# debe dar: [12, .12 ] 
list_1 = ([12, 2., .12, 3 ])

In [ ]:
def main(list_1 ): 
  respuesta = [] 
  for elementos  in  list_1 : 
    if int(str(elementos)[-1])==2 : 
      respuesta.append(elementos ) 
  print(respuesta ) 
main([12, 2., .12, 3  ])

no entiendo :(

## Extra 3

In [662]:
# La siguiente función debería aceptar un argumento, una lista con al menos 2 enteros
# La función debe devolver una lista en el mismo orden pero sin el segundo número más alto

# Por ejemplo:
# main([12, 2, 22, 3 ]) 
# debe dar:  [2, 22, 3 ] 

lista_1= [12, 2, 22, 3 ]
lista_2= lista_1[1:]

    #Corrige las lienas para que se de el resultado deseado

In [660]:
lista_1= [12, 2, 22, 3 ]
lista_2= lista_1[1:]
print(lista_2)

[2, 22, 3]

In [663]:
def  main ( list_1 ): 
    list_1 . sort () 
    x  =  [  i  for  i  in  list_1  if  i  !=  list_1 [ - 2 ]] 
    return  x 

main ([ 12 ,  2 ,  22 ,  3 ,  12 ])

[2, 3, 22]

In [ ]:
# La siguiente función debe aceptar dos argumentos, un número entero y una lista con números enteros
# La función debe devolver una lista con Verdadero y Falso para todos los enteros en la lista
# por el cual el primer argumento es divisible y False en caso contrario.

# Por ejemplo: 
# main(10, [12, 2, 22, 5 ]) 
# debe dar [False, True, False, True] 

def main(integer_1, list_1):
    list_2 = list_1[:]
    #Corrige las lienas para que se de el resultado deseado
    pass

In [ ]:
list_1= (10, [12, 2, 22, 5 ])

In [664]:
def  main ( integer_1 ,  list_1 ): 
  respuesta = [] 
  for  elementos  in  list_1 : 
    if  integer_1 %  elementos == 0 : 
      respuesta . append ( 'true' ) 
    elif  integer_1 %  elementos  != 0 : 
      respuesta . append ( 'false' ) 
  print ( respuesta ) 
main ( 10 ,  [ 12 ,  2 ,  22 ,  5  ])

['false', 'true', 'false', 'true']

In [ ]:
# La siguiente función debe aceptar un argumento, una lista con cadenas
# La función debe devolver un diccionario con como claves las cadenas y como valores
# las longitudes de las cadenas

# Por ejemplo: 
# main(["ad", "abc", "ab"]) 
# debe dar {"ad":2, "abc":3, "ab":2} 

def main(list_1):
    list_1 = list_1[:]
    #Corrige las lienas para que se de el resultado deseado
    pass

In [665]:
my_diccionario = {'ad': 2, 'abc':3,'ab': 2}
                #key o clave:Valor    #key:valor
                #1                    #2
print(my_diccionario)

{'ad': 2, 'abc': 3, 'ab': 2}

In [666]:
def  main ( list_1 ): 
  dictionary_1  =  {} 
  for  letras  in  list_1 : 
    dictionary_1 [ letras ] =  len ( letras ) 
  print ( dictionary_1 ) 
main ([ "ad" ,  "abc" ,  "ab" ])

{'ad': 2, 'abc': 3, 'ab': 2}

In [ ]:
# La siguiente función debe aceptar un argumento, una lista con cadenas

# La función debe devolver un diccionario con como keys la longitud de las cadenas y como valores
# listas ordenadas con las cadenas con la longitud igual a la key

# Por ejemplo: 
# main(["ab", "abc", "ad"]) 
# debe dar {2: ["ab", "ad"], 3: ["abc"]} 

def main(list_1):
    list_1 = list_1[:]
    #Corrige las lienas para que se de el resultado deseado
    pass

In [668]:
lista_1  = [ 'ab' , 'abc' , 'ad' ] 
dictionary_1  =  {} 
largo = [] 

for  letras  in  lista_1 : 
  largo . append ( len ( letras )) 
  sets =  set ( largo ) 
  for  key  in  sets : 
    if  len ( letras ) ==  key : 
      dictionary_1 [ key ] = letras 
print ( dictionary_1 )

{2: 'ad', 3: 'abc'}